name: SSH Tunnel via shell
version: 0.1
slug: ssh
description: >-
  'Permanent port forwarding through a simple SSH tunnel'
url: 'https://github.com/rfehren/home-assistant-addons'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
map:
  - 'config:rw'

options:
  hostname: ''
  ssh_port: 22
  username: 'rx'
  remote_forwarding:
    - '127.0.0.1:8123:172.17.0.1:8123'
  force_keygen: false
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding:
    - str
  force_keygen: bool
